name: helidroneimages
favicon: null
layout_spectrum: 0.5510638
typography_spectrum: 0.5787234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#FFFDFF'
    - '#918F92'
    - '#5D5A5E'
    - '#C5BC01'
  brandStrength: 0.4978724
  lightness: 0.2191489
  saturation: 0.822777
  rhythmicContrast: 0.153651
purpose: []
